### ISSUE TITLE
README specify only Ubuntu 18.04 and Debian 9, others?

### ISSUE THREAD

**Issue by Neustradamus** [rikcage/vst-php-selector#2]
@rikcage: I see:
"It has been tested and works on Ubuntu 18.04 and Debian 9."

It works for Debian 10, Debian 11, Ubuntu 20.04 LTS?

**Comment by rikcage** [comment]
This script is for VestaCP.
On this moment VestaCP does not support Debian 10, Debian 11, Ubuntu 20.04.
I don`t tested this script for Debian 10, Debian 11. 
In Ubuntu 20.04 this script install php 5.6-8.0, as default will be used php8.0 ($ php -v)

`# php -v`

`
PHP 8.0.9 (cli) (built: Jul 30 2021 13:03:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.9, Copyright (c), by Zend Technologies
`

`# php5.6 -v`

`
PHP 5.6.40-52+ubuntu20.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
`

Others you can check as `# php5.6 -v`, `# php7.0 -v` etc.
I think in Debian it shold work too.

**Comment by Neustradamus** [comment]
@rikcage: It has been solved?

**Comment by rikcage** [comment]
On this moment support of Debian 10, Debian 11, Ubuntu 20.04 is not required. Because VestaCP does not support Debian 10, Debian 11, Ubuntu 20.04.
But you can test it on an empty Debian, the script should install only php 5.6-8.0.

**Comment by Neustradamus** [comment]
@rikcage: Original VestaCP is dead and unsecured.

Now there are:
- https://www.hestiacp.com/
- https://www.myvestacp.com/

**Comment by anton-reutov** [comment]
> 
> 
> @rikcage: Original VestaCP is dead and unsecured.
> 
> Now there are:
> 
>     * https://www.hestiacp.com/
> 
>     * https://www.myvestacp.com/

What makes you think that the project is dead and who told you this? The information does not correspond to reality. Yes, Sergey is busy, everything is moving very slowly, but a new frontend interface has already been written, and now I am preparing a release with fixes. Security bugs already fixed, I will finish working on the fix release and we will publish it.

**Comment by anton-reutov** [comment]
And stop misinforming others about the project is "dead"

**Comment by Neustradamus** [comment]
@anton-reutov: You can read here: https://github.com/serghey-rodin/vesta/issues/2006
It is not me who think that VestaCP is now dead and there are now 2 forks.

**Comment by anton-reutov** [comment]
If Vesta dies, I'll let you know. Don't worry :))))
